# 1 - Build BTC price + news feature dataset

**Price:** `BTC_raw` (Mongo, hourly OHLCV).  
**News:** `bitcoin-news-data/datasets/news.csv` (~34k articles, **2025-07-17 -> 2025-11-23**); coins from `CATEGORIES`/`TAGS`, plus **FinBERT** (finance-tuned) headline sentiment as the directional signal.

Output: `btc_features.csv` for `2_modeling.ipynb`.

> FinBERT runs on CPU; the first pass over ~34k headlines is slow (minutes) but per-headline scores are **cached to `headline_sentiment.csv`**, so reruns are instant. Assumes news `DATETIME` is UTC.

In [24]:
import os
import numpy as np
import pandas as pd
from pymongo import MongoClient

MONGO_URI = os.getenv('MONGO_URI', 'mongodb://admin:admin@localhost:27027/?authSource=admin')
MONGO_DB  = os.getenv('MONGO_DB', 'news_data')
NEWS_CSV  = os.getenv('NEWS_CSV', r'C:/Users/Admin/Code/Github/bitcoin-news-data/datasets/news.csv')
COIN = 'BTC'
WINDOW_START = pd.Timestamp('2025-07-17', tz='UTC')
WINDOW_END   = pd.Timestamp('2025-11-24', tz='UTC')  # exclusive -> through Nov 23
OUT_CSV = 'btc_features.csv'
SENT_CACHE = 'headline_sentiment.csv'
FINBERT_MODEL = 'ProsusAI/finbert'

db = MongoClient(MONGO_URI)[MONGO_DB]
print('BTC_raw docs:', db[f'{COIN}_raw'].count_documents({}))

BTC_raw docs: 9511

## Price data + technical indicators

In [25]:
price = pd.DataFrame(list(db[f'{COIN}_raw'].find({}, {'_id': 0})))
price['datetime'] = pd.to_datetime(price['datetime'], utc=True)
price = price.sort_values('datetime').drop_duplicates('datetime').set_index('datetime')
price = price[['open', 'high', 'low', 'close', 'volumefrom', 'volumeto']].astype(float)
print(price.shape, price.index.min(), '->', price.index.max())
price.tail()

(9511, 6) 2025-05-14 00:00:00+00:00 -> 2026-06-14 06:00:00+00:00

,open,high,low,close,volumefrom,volumeto
datetime,,,,,,
2026-06-14 02:00:00+00:00,64563.00,64636.00,64476.01,64490.01,260.23317,1.680181e+07
2026-06-14 03:00:00+00:00,64490.01,64545.40,64466.00,64545.30,155.67419,1.004188e+07
2026-06-14 04:00:00+00:00,64545.30,64563.48,64325.61,64339.07,253.74802,1.634483e+07
2026-06-14 05:00:00+00:00,64339.07,64411.20,64293.41,64338.00,429.46847,2.763819e+07
2026-06-14 06:00:00+00:00,64338.00,64487.80,64232.12,64258.00,746.67588,4.804312e+07

In [26]:
from ta.momentum import RSIIndicator
from ta.trend import MACD, SMAIndicator
from ta.volatility import BollingerBands

feat = pd.DataFrame(index=price.index)
feat['close'] = price['close']
feat['volume'] = price['volumeto']
feat['ret_1h'] = price['close'].pct_change()
feat['ret_3h'] = price['close'].pct_change(3)
feat['vol_change'] = price['volumeto'].pct_change()
feat['rsi_14'] = RSIIndicator(price['close'], window=14).rsi()
macd = MACD(price['close'])
feat['macd'] = macd.macd()
feat['macd_signal'] = macd.macd_signal()
sma20 = SMAIndicator(price['close'], window=20).sma_indicator()
feat['sma20_ratio'] = price['close'] / sma20 - 1
bb = BollingerBands(price['close'], window=20)
feat['bb_pct'] = (price['close'] - bb.bollinger_lband()) / (bb.bollinger_hband() - bb.bollinger_lband())
feat.tail()

,close,volume,ret_1h,ret_3h,vol_change,rsi_14,macd,macd_signal,sma20_ratio,bb_pct
datetime,,,,,,,,,,
2026-06-14 02:00:00+00:00,64490.01,1.680181e+07,-0.001131,0.000496,-0.683299,63.866506,225.153454,203.710763,0.004750,0.794284
2026-06-14 03:00:00+00:00,64545.30,1.004188e+07,0.000857,-0.000305,-0.402334,65.280315,223.852801,207.739171,0.005064,0.815048
2026-06-14 04:00:00+00:00,64339.07,1.634483e+07,-0.003195,-0.003468,0.627666,56.413742,203.831345,206.957606,0.001437,0.595821
2026-06-14 05:00:00+00:00,64338.00,2.763819e+07,-0.000017,-0.002357,0.690944,56.370961,185.736799,202.713444,0.000957,0.572594
2026-06-14 06:00:00+00:00,64258.00,4.804312e+07,-0.001243,-0.004451,0.738288,53.127062,163.061736,194.783103,-0.000610,0.447606

## News: coin mentions (tags) + FinBERT headline sentiment

In [27]:
COIN_ALIASES = {
    'btc': ['BTC', 'BITCOIN'], 'eth': ['ETH', 'ETHEREUM'], 'xrp': ['XRP', 'RIPPLE'],
    'sol': ['SOL', 'SOLANA'], 'bnb': ['BNB', 'BINANCE'], 'ada': ['ADA', 'CARDANO'],
    'doge': ['DOGE', 'DOGECOIN'], 'xlm': ['XLM', 'STELLAR'], 'link': ['LINK', 'CHAINLINK'],
    'avax': ['AVAX', 'AVALANCHE'], 'uni': ['UNI', 'UNISWAP'], 'ltc': ['LTC', 'LITECOIN'],
    'matic': ['MATIC', 'POLYGON'], 'atom': ['ATOM', 'COSMOS'], 'dot': ['DOT', 'POLKADOT'],
}
ALIAS2COIN = {a: c for c, al in COIN_ALIASES.items() for a in al}

def coins_of(cats, tags):
    toks = set()
    for v in (cats, tags):
        if isinstance(v, str):
            toks |= {t.strip().upper() for t in v.split('|')}
    return {ALIAS2COIN[t] for t in toks if t in ALIAS2COIN}

news = pd.read_csv(NEWS_CSV, usecols=['DATETIME', 'HEADLINE', 'URL', 'CATEGORIES', 'TAGS'])
news['DATETIME'] = pd.to_datetime(news['DATETIME'], utc=True, errors='coerce')
news = news.dropna(subset=['DATETIME']).reset_index(drop=True)
cset = [coins_of(c, t) for c, t in zip(news['CATEGORIES'], news['TAGS'])]
news['btc'] = [int('btc' in s) for s in cset]
news['ncoins'] = [len(s) for s in cset]
news['hour'] = news['DATETIME'].dt.floor('h')
print('news rows:', len(news), '| btc-tagged:', round(news['btc'].mean(), 3))

news rows: 34000 | btc-tagged: 0.905

In [28]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

def finbert_net(headlines, batch=64):
    """Return P(positive) - P(negative) per headline (signed sentiment in [-1, 1])."""
    tok = AutoTokenizer.from_pretrained(FINBERT_MODEL)
    mdl = AutoModelForSequenceClassification.from_pretrained(FINBERT_MODEL).eval()
    id2 = {i: l.lower() for i, l in mdl.config.id2label.items()}
    pos_i = next(i for i, l in id2.items() if l == 'positive')
    neg_i = next(i for i, l in id2.items() if l == 'negative')
    out = np.zeros(len(headlines), dtype=float)
    for i in range(0, len(headlines), batch):
        chunk = [h if isinstance(h, str) else '' for h in headlines[i:i + batch]]
        enc = tok(chunk, padding=True, truncation=True, max_length=64, return_tensors='pt')
        with torch.no_grad():
            probs = torch.softmax(mdl(**enc).logits, dim=1).numpy()
        out[i:i + len(chunk)] = probs[:, pos_i] - probs[:, neg_i]
        if i % (batch * 20) == 0:
            print(f'  FinBERT scoring: {i}/{len(headlines)} ({100 * i // max(len(headlines), 1)}%)', flush=True)
    print(f'  FinBERT scoring: {len(headlines)}/{len(headlines)} (100%) done', flush=True)
    return out

cache = {}
if os.path.exists(SENT_CACHE):
    cache = pd.read_csv(SENT_CACHE).set_index('URL')['sent'].to_dict()
missing = news[~news['URL'].isin(cache)].drop_duplicates('URL')
if len(missing):
    print(f'FinBERT scoring {len(missing)} new headlines (CPU, one-time)...')
    sc = finbert_net(missing['HEADLINE'].tolist())
    cache.update(dict(zip(missing['URL'], sc)))
    pd.Series(cache, name='sent').rename_axis('URL').to_csv(SENT_CACHE)
news['sent'] = news['URL'].map(cache).astype(float)
print('cached headlines:', len(cache), '| mean sentiment:', round(news['sent'].mean(), 3))

FinBERT scoring 33565 new headlines (CPU, one-time)...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

  FinBERT scoring: 0/33565 (0%)
  FinBERT scoring: 1280/33565 (3%)
  FinBERT scoring: 2560/33565 (7%)
  FinBERT scoring: 3840/33565 (11%)
  FinBERT scoring: 5120/33565 (15%)
  FinBERT scoring: 6400/33565 (19%)
  FinBERT scoring: 7680/33565 (22%)
  FinBERT scoring: 8960/33565 (26%)
  FinBERT scoring: 10240/33565 (30%)
  FinBERT scoring: 11520/33565 (34%)
  FinBERT scoring: 12800/33565 (38%)
  FinBERT scoring: 14080/33565 (41%)
  FinBERT scoring: 15360/33565 (45%)
  FinBERT scoring: 16640/33565 (49%)
  FinBERT scoring: 17920/33565 (53%)
  FinBERT scoring: 19200/33565 (57%)
  FinBERT scoring: 20480/33565 (61%)
  FinBERT scoring: 21760/33565 (64%)
  FinBERT scoring: 23040/33565 (68%)
  FinBERT scoring: 24320/33565 (72%)
  FinBERT scoring: 25600/33565 (76%)
  FinBERT scoring: 26880/33565 (80%)
  FinBERT scoring: 28160/33565 (83%)
  FinBERT scoring: 29440/33565 (87%)
  FinBERT scoring: 30720/33565 (91%)
  FinBERT scoring: 32000/33565 (95%)
  FinBERT scoring: 33280/33565 (99%)
  FinBERT scoring: 33565/33565 (100%) done
cached headlines: 33565 | mean sentiment: 0.078

In [29]:
g = news.groupby('hour')
news_hourly = g.agg(
    btc_mentions=('btc', 'sum'),
    n_articles=('btc', 'size'),
    total_coin_mentions=('ncoins', 'sum'),
    sent_mean=('sent', 'mean'),
).rename_axis('datetime')
news_hourly['btc_share'] = news_hourly['btc_mentions'] / news_hourly['n_articles']
news_hourly['sent_net'] = g['sent'].apply(lambda s: (s > 0.1).mean() - (s < -0.1).mean())
news_hourly['btc_sent_mean'] = news[news['btc'] == 1].groupby('hour')['sent'].mean()
news_hourly[['sent_net', 'btc_sent_mean']] = news_hourly[['sent_net', 'btc_sent_mean']].fillna(0)
news_hourly.tail()

,btc_mentions,n_articles,total_coin_mentions,sent_mean,btc_share,sent_net,btc_sent_mean
datetime,,,,,,,
2025-11-22 23:00:00+00:00,4,4,5,-0.026868,1.00,0.00,-0.026868
2025-11-23 00:00:00+00:00,5,5,5,-0.188516,1.00,-0.40,-0.188516
2025-11-23 01:00:00+00:00,3,4,3,0.264665,0.75,0.25,0.330291
2025-11-23 02:00:00+00:00,2,2,4,0.330462,1.00,0.00,0.330462
2025-11-23 03:00:00+00:00,2,2,2,-0.112008,1.00,0.00,-0.112008

## Join price + news, restrict to overlap window

In [30]:
df = feat.join(news_hourly, how='left')
vol_cols = ['btc_mentions', 'n_articles', 'total_coin_mentions', 'btc_share']
sent_cols = ['sent_mean', 'sent_net', 'btc_sent_mean']
for col in vol_cols + sent_cols:
    df[col] = df[col].fillna(0)
df['btc_mentions_3h'] = df['btc_mentions'].rolling(3, min_periods=1).sum()

df = df[(df.index >= WINDOW_START) & (df.index < WINDOW_END)]
df = df.dropna()
print('dataset shape:', df.shape)
print('hours with news:', int((df['n_articles'] > 0).sum()), '/', len(df))
df.head()

dataset shape: (3120, 18)
hours with news: 3042 / 3120

,close,volume,ret_1h,ret_3h,vol_change,rsi_14,macd,macd_signal,sma20_ratio,bb_pct,btc_mentions,n_articles,total_coin_mentions,sent_mean,btc_share,sent_net,btc_sent_mean,btc_mentions_3h
datetime,,,,,,,,,,,,,,,,,,
2025-07-17 00:00:00+00:00,118894.33,3.796278e+07,0.002225,-0.003381,-0.069338,52.414603,268.531395,321.306935,0.000082,0.505253,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2025-07-17 01:00:00+00:00,118149.70,1.010368e+08,-0.006263,-0.004127,1.661470,44.882633,183.836126,293.812773,-0.006298,0.071777,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2025-07-17 02:00:00+00:00,118330.57,7.190581e+07,0.001531,-0.002528,-0.288321,46.879411,129.812811,261.012781,-0.004800,0.170854,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2025-07-17 03:00:00+00:00,118128.80,5.339443e+07,-0.001705,-0.006439,-0.257439,44.924188,69.911892,222.792603,-0.006472,0.061424,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2025-07-17 04:00:00+00:00,118485.40,4.604592e+07,0.003019,0.002841,-0.137627,48.974694,50.630979,188.360278,-0.003382,0.274540,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
df.to_csv(OUT_CSV)
print('saved', OUT_CSV, df.shape)
df[['close'] + vol_cols + ['btc_mentions_3h'] + sent_cols].describe()

saved btc_features.csv (3120, 18)

,close,btc_mentions,n_articles,total_coin_mentions,btc_share,btc_mentions_3h,sent_mean,sent_net,btc_sent_mean
count,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000
mean,111811.549824,9.858654,10.897436,15.011859,0.854490,29.575962,0.070406,0.172448,0.071178
std,7814.978366,6.737383,7.116067,10.901708,0.238328,17.649522,0.246205,0.360523,0.252430
min,82207.840000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.963723,-1.000000,-0.963983
25%,109448.870000,5.000000,6.000000,7.000000,0.833333,16.000000,-0.062694,0.000000,-0.059589
50%,113133.160000,9.000000,10.000000,13.000000,0.928571,26.000000,0.073647,0.181818,0.067371
75%,117031.205000,14.000000,15.000000,21.000000,1.000000,40.000000,0.220900,0.400000,0.227133
max,126011.180000,40.000000,42.000000,66.000000,1.000000,101.000000,0.932612,1.000000,0.932612